/*
* Generated file
*
* Generated from: yang module name: nicira-extension-impl yang module local name: nicira-extension-provider-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Thu Jul 31 10:18:29 CEST 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.openflowplugin.nx.config.impl;
public class ConfigurableNiciraExtensionProviderModuleFactory extends org.opendaylight.controller.config.yang.openflowplugin.nx.config.impl.AbstractConfigurableNiciraExtensionProviderModuleFactory {

}
