/*
* Generated file
*
* Generated from: yang module name: openflowjava-nx-config yang module local name: openflow-extension-nicira
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Thu Jul 31 09:21:45 CEST 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.openflowjava.nx;
public class NiciraExtensionProviderModuleFactory extends org.opendaylight.controller.config.yang.openflowjava.nx.AbstractNiciraExtensionProviderModuleFactory {

}
