[tox]
minversion = 1.6.0
envlist = docs pre-commit
skipsdist = true

[testenv:docs]
deps = -rdocs/requirements.txt
commands = sphinx-build -W -n -b html -d {envtmpdir}/doctrees ./docs/ {envtmpdir}/html

[testenv:pre-commit]
basepython = python3
deps = pre-commit
commands =
    pre-commit run --all-files
    pre-commit run gitlint --hook-stage commit-msg --commit-msg-filename .git/COMMIT_EDITMSG
