/*
* Generated file
*
* Generated from: yang module name: forwardingrules-sync yang module local name: forwardingrules-sync
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon Feb 01 13:26:52 CET 2016
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.openflowplugin.applications.config.yang.forwardingrules_sync;
public class ForwardingRulesSyncModuleFactory extends org.opendaylight.openflowplugin.applications.config.yang.forwardingrules_sync.AbstractForwardingRulesSyncModuleFactory {

}
