/*
* Generated file
*
* Generated from: yang module name: forwardingrules-manager yang module local name: forwardingrules-manager
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Thu Apr 23 19:20:17 CEST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.openflowplugin.applications.config.yang.forwardingrules_manager;
public class ForwardingRulesManagerModuleFactory extends org.opendaylight.openflowplugin.applications.config.yang.forwardingrules_manager.AbstractForwardingRulesManagerModuleFactory {

}
