/*
* Generated file
*
* Generated from: yang module name: test-provider-impl yang module local name: test-provider-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Thu Jul 24 21:33:31 CEST 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.test_provider.impl;
public class TestProviderModuleFactory extends org.opendaylight.controller.config.yang.config.test_provider.impl.AbstractTestProviderModuleFactory {

}
