/*
 * (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 */


package org.opendaylight.of.controller;

/**
 * A destination for alerts generated by the OpenFlow controller.
 *
 * @author Simon Hunt
 */
public interface AlertSink {

    /** Posts an alert to the sink.
     *
     * @param alert the alert
     */
    void postAlert(Alert alert);

}
