/*
* Generated file
*
* Generated from: yang module name: flowprogrammer-impl yang module local name: flowprogrammer-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Tue Sep 15 10:24:41 CST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.openflowplugin.flowprogrammer.config.yang.impl;
public class FlowProgrammerImplModuleFactory extends org.opendaylight.openflowplugin.flowprogrammer.config.yang.impl.AbstractFlowProgrammerImplModuleFactory {

}
