/*
* Generated file
*
* Generated from: yang module name: openflowjava-nx-api-config yang module local name: openflowjava-extension-nicira-api
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Thu Jul 31 09:12:34 CEST 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.openflowjava.nx.api;
public class NiciraExtensionApiProviderModuleFactory extends org.opendaylight.controller.config.yang.openflowjava.nx.api.AbstractNiciraExtensionApiProviderModuleFactory {

}
